import type { Listing } from './types.ts'

/**
 * Extra tiles so every Explore shelf can scroll past the first peek.
 */
export const EXTRA_LISTINGS: readonly Listing[] = [
  {
    id: 'viewed-madrid',
    kind: 'stay',
    title: 'Malasaña walk-up',
    tripName: 'Gran Vía nights',
    location: 'Madrid, Spain',
    dates: '3–6 Nov',
    priceEuros: 1120,
    priceSuffix: 'total',
    rating: { score: 4.77, count: 204 },
    imageUrl:
      'https://images.unsplash.com/photo-1543785734-4b6e564642f8?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Gran Vía in Madrid at dusk',
  },
  {
    id: 'viewed-paris',
    kind: 'stay',
    title: 'Left Bank hotel',
    tripName: 'Seine mornings',
    location: 'Paris, France',
    dates: '11–14 Oct',
    priceEuros: 1340,
    priceSuffix: 'total',
    rating: { score: 4.83, count: 418 },
    imageUrl:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Seine and Île de la Cité in Paris',
  },
  {
    id: 'viewed-florence',
    kind: 'stay',
    title: 'Oltrarno rooms',
    tripName: 'Duomo walk',
    location: 'Florence, Italy',
    dates: '18–21 Oct',
    priceEuros: 890,
    priceSuffix: 'total',
    rating: { score: 4.91, count: 163 },
    imageUrl:
      'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Florence rooftops toward the Duomo',
  },
  {
    id: 'weekend-milan',
    kind: 'stay',
    title: 'Brera apartment',
    tripName: 'Galleria weekend',
    location: 'Milan, Italy',
    dates: 'Fri–Sun',
    priceEuros: 460,
    priceSuffix: 'total',
    rating: { score: 4.72, count: 119 },
    imageUrl:
      'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Galleria Vittorio Emanuele II in Milan',
  },
  {
    id: 'weekend-seville',
    kind: 'stay',
    title: 'Santa Cruz house',
    tripName: 'Orange courtyards',
    location: 'Seville, Spain',
    dates: 'Fri–Sun',
    priceEuros: 355,
    priceSuffix: 'total',
    rating: { score: 4.86, count: 201 },
    imageUrl:
      'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Plaza de España in Seville',
  },
  {
    id: 'weekend-edinburgh',
    kind: 'stay',
    title: 'Old Town stair house',
    tripName: 'Castle hill',
    location: 'Edinburgh, United Kingdom',
    dates: 'Fri–Sun',
    priceEuros: 390,
    priceSuffix: 'total',
    rating: { score: 4.8, count: 142 },
    imageUrl:
      'https://images.unsplash.com/photo-1596484552834-aa8ec1210412?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Edinburgh Castle on the hill',
  },
  {
    id: 'exp-market-paris',
    kind: 'experience',
    title: 'Morning market with a Paris cook',
    tripName: 'Rue Cler shop',
    location: 'Paris, France',
    dates: '3 hours',
    priceEuros: 78,
    priceSuffix: 'person',
    rating: { score: 4.94, count: 287 },
    imageUrl:
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Cook preparing food at a market stall',
  },
  {
    id: 'exp-canal-ams',
    kind: 'experience',
    title: 'Bike the Amsterdam canals',
    tripName: 'Canal ride',
    location: 'Amsterdam, Netherlands',
    dates: '2 hours',
    priceEuros: 36,
    priceSuffix: 'person',
    rating: { score: 4.88, count: 512 },
    imageUrl:
      'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Bicycles along an Amsterdam canal',
  },
  {
    id: 'exp-wine-tuscany',
    kind: 'experience',
    title: 'Chianti tasting in the hills',
    tripName: 'Chianti afternoon',
    location: 'Greve in Chianti, Italy',
    dates: 'Half day',
    priceEuros: 95,
    priceSuffix: 'person',
    rating: { score: 4.96, count: 176 },
    imageUrl:
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Tuscan hillside town in late light',
  },
  {
    id: 'deal-budapest',
    kind: 'stay',
    title: 'Pest-side studio',
    tripName: 'Danube deal',
    location: 'Budapest, Hungary',
    dates: '8–11 Nov',
    priceEuros: 176,
    priceSuffix: 'total',
    rating: { score: 4.68, count: 233 },
    imageUrl:
      'https://images.unsplash.com/photo-1551867633-194f125bddfa?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Parliament on the Danube in Budapest',
  },
  {
    id: 'deal-krakow',
    kind: 'stay',
    title: 'Kazimierz loft',
    tripName: 'Vistula deal',
    location: 'Kraków, Poland',
    dates: '4–7 Nov',
    priceEuros: 162,
    priceSuffix: 'total',
    rating: { score: 4.71, count: 158 },
    imageUrl:
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Cloth Hall on Kraków’s main square',
  },
  {
    id: 'deal-valencia',
    kind: 'stay',
    title: 'Ruzafa flat',
    tripName: 'Turia deal',
    location: 'Valencia, Spain',
    dates: '16–19 Nov',
    priceEuros: 188,
    priceSuffix: 'total',
    rating: { score: 4.66, count: 97 },
    imageUrl:
      'https://images.unsplash.com/photo-1558642084-fd07fae5348e?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'City of Arts and Sciences in Valencia',
  },
  {
    id: 'flight-ber',
    kind: 'flight',
    title: 'Berlin',
    route: 'ARN – BER',
    city: 'Berlin',
    dates: 'Thu 8 – Mon 12 Oct',
    priceEuros: 44,
    rating: { score: 4.2, count: 870 },
  },
  {
    id: 'flight-ams',
    kind: 'flight',
    title: 'Amsterdam',
    route: 'ARN – AMS',
    city: 'Amsterdam',
    dates: 'Fri 16 – Mon 19 Oct',
    priceEuros: 61,
    rating: { score: 4.35, count: 1100 },
  },
  {
    id: 'flight-bcn',
    kind: 'flight',
    title: 'Barcelona',
    route: 'ARN – BCN',
    city: 'Barcelona',
    dates: 'Sat 17 – Wed 21 Oct',
    priceEuros: 53,
    rating: { score: 4.28, count: 760 },
  },
  {
    id: 'last-madrid',
    kind: 'stay',
    title: 'Lavapiés room tonight',
    tripName: 'Madrid tonight',
    location: 'Madrid, Spain',
    dates: 'Tonight – Sun',
    priceEuros: 118,
    priceSuffix: 'night',
    rating: { score: 4.51, count: 73 },
    imageUrl:
      'https://images.unsplash.com/photo-1464790719320-47dd4c1e0c0c?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Warm evening street in Madrid',
  },
  {
    id: 'last-paris',
    kind: 'stay',
    title: 'Marais attic tonight',
    tripName: 'Paris tonight',
    location: 'Paris, France',
    dates: 'Tonight – Mon',
    priceEuros: 168,
    priceSuffix: 'night',
    rating: { score: 4.62, count: 141 },
    imageUrl:
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Eiffel Tower from a Paris rooftop',
  },
  {
    id: 'last-prague',
    kind: 'stay',
    title: 'Malá Strana room',
    tripName: 'Prague last call',
    location: 'Prague, Czechia',
    dates: 'Tomorrow – Tue',
    priceEuros: 99,
    priceSuffix: 'night',
    rating: { score: 4.58, count: 66 },
    imageUrl:
      'https://images.unsplash.com/photo-1592906209472-a8ea6ba071c3?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Prague rooftops at blue hour',
  },
  {
    id: 'city-paris',
    kind: 'stay',
    title: 'Marais courtyard',
    tripName: 'Marais break',
    location: 'Paris, France',
    dates: 'City break',
    priceEuros: 165,
    priceSuffix: 'night',
    rating: { score: 4.74, count: 329 },
    imageUrl:
      'https://images.unsplash.com/photo-1522093007474-d86e9bf7ba6f?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Paris street with café chairs',
  },
  {
    id: 'city-london',
    kind: 'stay',
    title: 'Shoreditch loft',
    tripName: 'East End break',
    location: 'London, United Kingdom',
    dates: 'City break',
    priceEuros: 152,
    priceSuffix: 'night',
    rating: { score: 4.59, count: 284 },
    imageUrl:
      'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Tower Bridge over the Thames',
  },
  {
    id: 'city-milan',
    kind: 'stay',
    title: 'Navigli apartment',
    tripName: 'Navigli break',
    location: 'Milan, Italy',
    dates: 'City break',
    priceEuros: 128,
    priceSuffix: 'night',
    rating: { score: 4.67, count: 191 },
    imageUrl:
      'https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Canal-side street in Milan',
  },
]
